version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: 'docker/server/Dockerfile'
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    environment:
      DATABASE: &db 'postgresql://postgres:postgres@postgres:5432/postgres'
      SECRET_KEY: &secret_key ${SECRET_KEY:-secret_key}

      WORKER_MAX_REQUESTS: ${WORKER_MAX_REQUESTS:-50000}
      WORKER_LIMIT_CONCURRENCY: ${WORKER_LIMIT_CONCURRENCY:-500}

      LOGGING_LEVEL: 'DEBUG'
      PYTHONASYNCIODEBUG: 'true'
      PYTEST_ADDOPTS: ${PYTEST_ADDOPTS:-}
    ports:
      - '${PORT:-8000}:8000'
    volumes:
      - '.:/app/'
    restart: always
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  migrations:
    build:
      context: .
      dockerfile: 'docker/server/Dockerfile'
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    command: alembic upgrade head
    environment:
      DATABASE: *db
      SECRET_KEY: *secret_key
    volumes:
      - '.:/app/'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:11.2'
    environment:
      POSTGRES_PASSWORD: 'postgres'
