version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: 'docker/server/Dockerfile'
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    environment:
      DATABASE: &db 'postgresql://postgres:postgres@postgres:5432/postgres'
      SECRET_KEY: ${SECRET_KEY:-secret_key}

      MAX_REQUESTS: ${MAX_REQUESTS:-50000}
      LIMIT_CONCURRENCY: ${LIMIT_CONCURRENCY:-500}

      SECURE_COOKIES: 'false'
      LOGGING_LEVEL: 'DEBUG'
      PYTHONASYNCIODEBUG: 'true'
      PYTEST_ADDOPTS: ${PYTEST_ADDOPTS:-}
    ports:
      - '${PORT:-8000}:8000'
    volumes:
      - '.:/app/'
      # - './docker/server/start.sh:/start.sh:ro'
    restart: always
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: 'postgres:11.2'
    environment:
      POSTGRES_PASSWORD: 'postgres'
